LD_LIBRARY_PATH=${CATALINA_BASE}/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

LANG=en_US.UTF-8
export LANG

if [ ! -z "$INTERMAIL" ] ; then
  CATALINA_PID=$INTERMAIL/tmp/webtop.pid
else
  CATALINA_PID=$CATALINA_BASE/logs/catalina-daemon.pid
fi
export CATALINA_PID

CATALINA_OPTS="$CATALINA_OPTS -Dfile.encoding=UTF8"
CATALINA_OPTS="$CATALINA_OPTS -XX:+UseConcMarkSweepGC"
CATALINA_OPTS="$CATALINA_OPTS -XX:+CMSClassUnloadingEnabled"
CATALINA_OPTS="$CATALINA_OPTS -XX:MaxJavaStackTraceDepth=0"
CATALINA_OPTS="$CATALINA_OPTS -Djava.awt.headless=true"
CATALINA_OPTS="$CATALINA_OPTS -Djava.net.preferIPv4Stack=true"
CATALINA_OPTS="$CATALINA_OPTS -Xms256m"
CATALINA_OPTS="$CATALINA_OPTS -Xmx6144m"
CATALINA_OPTS="$CATALINA_OPTS -XX:PermSize=128m"
CATALINA_OPTS="$CATALINA_OPTS -XX:MaxPermSize=1024m"
export CATALINA_OPTS

_JAVA_SR_SIGNUM=12
export _JAVA_SR_SIGNUM
echo 'All set!'
